x86/mm: Check if PTRS_PER_PMD is defined before use
Compiler is not happy about PTRS_PER_PMD being undefined

In file included from arch/x86/kernel/head_32.S:29:
arch/x86/include/asm/pgtable_32.h:59:5: error: "PTRS_PER_PMD" is not defined, evaluates to 0 [-Werror=undef]
   59 | #if PTRS_PER_PMD > 1

Add a check to make sure PTRS_PER_PMD is defined before use.

Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>